config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'blogs#index'
  resources :blogs
  namespace :blogs do
    post '/:id/comments' => 'comments#create', as: 'comment'
    delete '/comment/:id' => 'comments#destroy', as: 'comment_delete'
  end

end

app/models/blog.rb
class Blog
  include Mongoid::Document
  include Mongoid::Paperclip

  field :title, type: String
  field :content, type: String
  field :status, type: Boolean, default: true

  has_mongoid_attached_file :image

  validates_presence_of :title, :content
  validates_uniqueness_of :title
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  has_many :comments, class_name: 'Blogs::Comment'
  belongs_to :user
end

app/models/blogs/comment.rb
class Blogs::Comment
  include Mongoid::Document
  include Mongoid::Timestamps

  field :comment, type: String
  field :author,  type: String

  validates_presence_of :comment, :author

  belongs_to :blog
  belongs_to :user
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time

  has_many :blogs
  has_many :comments, class_name: 'Blogs::Comment'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authenticated_controller.rb
class AuthenticatedController < ApplicationController
	before_filter :authenticate_user!
end

app/controllers/blogs/comments_controller.rb
class Blogs::CommentsController < AuthenticatedController

	def create
		@blog = Blog.find(params[:id])
		@comment = Blogs::Comment.new(comment_params)
		@comment.user = current_user
		@comment.save
		if @comment.errors.count > 0
			flash[:alert] = @comment.errors.full_messages.join(', ')
		end
		if @comment.save
			@comment.blog = @blog
			@comment.save
			redirect_to blog_path(@blog)
		else
			render '/blogs/show'
		end
	end

	def destroy
		@comment = Blogs::Comment.find(params[:id])
		raise_error
		@blog = @comment.blog
		@comment.destroy
		redirect_to @blog
	end

	def raise_error
		if @comment.user != current_user
		  raise "You are not authorized to do this operation. Incident will pe reported with IP."
		end
	end

	def comment_params
		params.require(:blogs_comment).permit(:comment, :author)
	end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  before_action :set_blog, only: [:edit, :show, :update, :destroy]
  before_action :raise_error, only: [:edit, :update, :destroy ]
  before_filter :authenticate_user!, except: [:index, :show]

  def index
    @blogs = Blog.all
  end

  def edit
  end

  def show
    @comment = Blogs::Comment.new
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)
    @blog.user = current_user
    if @blog.save
      redirect_to blog_path(@blog), flash: {notice: "Blog was created!"}
    else
      render :new
    end
  end

  def update
    if @blog.update(blog_params)
      redirect_to blog_path(@blog), flash: {notice: "Blog was updated!"}
    else
      render :edit
    end
  end

  def destroy
    @blog.destroy
    redirect_to root_path, flash: {notice: "Blog was deleted!"}
  end

  def raise_error
    if @blog.user != current_user
      raise "You are not authorized to do this operation. Incident will pe reported with IP."
    end
  end

  def set_blog
    @blog = Blog.find(params[:id])
  end

  def blog_params
    params.require(:blog).permit(:title, :content, :image)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@blogs = Blog.all
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<% if @blog.errors.count > 0 %>
	<% @blog.errors.full_messages.each do |error| %>
		<p class="alert"><%= error %></p>
	<% end %>
<% end %>
<%= form_for @blog do |f| %>
	<%= f.text_field :title %><br/>
	<%= f.file_field :image %>
	<%= f.text_area :content %><br/>
	<%= f.submit %>
<% end %>

app/views/blogs/edit.html.erb
<h1>Edit Blog</h1>

<%= render 'form' %>

app/views/blogs/index.html.erb
<h1>Blogs | <%= link_to 'New', new_blog_path %></h1>
<% @blogs.each do |blog| %>
	<article>
		<h3><%= link_to blog.title, blog_path(blog) %> 
			<%# if blog.user == current_user %>
			| <%= link_to 'Edit', edit_blog_path(blog) %> | <%= link_to 'Delete', blog_path(blog), method: :delete, data: {confirm: "Are you sure?"} %>
			<%# end %>
		</h3>
		<p><%= blog.content %></p>
	</article>
<% end %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form' %>

app/views/blogs/show.html.erb
<h1><%= @blog.title %></h1>
<em>by <%= @blog.user.email %></em>
<%= image_tag @blog.image.url %>
<p><%= @blog.content %></p>
<h2>Comments: </h2>
<% @blog.comments.each do |comment| %>
<p><%= comment.author %> says "<%= comment.comment %>" at <%= comment.created_at %>
	<% if comment.user == current_user %>
 <%= link_to 'X', blogs_comment_delete_path(comment), method: :delete, data: {confirm: "Are you sure?"} %></p>
 <% end %>
<% end %>
<%= form_for @comment, url: blogs_comment_path(@blog) do |f| %>
<%= f.text_field :author %>
<%= f.text_area :comment %>
<%= f.submit %>
<% end %>
<%= link_to 'Back', root_path %>

app/views/home/index.html.erb
<ul>
	<% @blogs.each do |blog| %>
		<li
			<% if blog.status == true %>
			style="color: #0f0;"
			<% else %>
			style="color: #f00;"
			<% end %>
		><%= blog.title %> => <%= blog.status %></li>
	<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mongone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if flash[:notice] %>
	<div class="notice"><%= flash[:notice] %></div>
<% end %>
<% if flash[:alert] %>
	<div class="alert"><%= flash[:alert] %></div>
<% end %>
<% if user_signed_in? %>
	<%= link_to 'Logout', destroy_user_session_path, method: :delete %>
<% else %>
	<%= link_to 'Login', new_user_session_path %>
<% end %>
<%= yield %>

</body>
</html>